#=========================================
# Cấu hình riêng cho môi trường DEV
#=========================================

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Database (Local Postgres)
spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=rootpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Actuator (Mở toàn bộ endpoint để dễ debug)
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
