#=========================================
# Cấu hình riêng cho môi trường PROD
#=========================================

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://discovery-server:8761/eureka/}

# Database (Production)
spring.datasource.url=${USER_DB_URL:jdbc:postgresql://postgres-server:5432/user_db}
spring.datasource.username=${USER_DB_USERNAME:postgres}
spring.datasource.password=${USER_DB_PASSWORD:rootpassword}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Actuator (Chỉ mở các endpoint an toàn)
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=never
