# =========================================
# Common Configurations (User Service)
# =========================================
server.port=8081
spring.application.name=user-service
eureka.instance.prefer-ip-address=true

# Swagger cho user-service & Proxy (Common)
springdoc.swagger-ui.enabled=false
server.forward-headers-strategy=framework

# gRPC Server (Common)
grpc.server.port=9091
grpc.server.address=0.0.0.0

# (Other environment-specific properties like Database, Eureka, 
# and Actuator exposure are moved to user-service-dev.properties 
# and user-service-prod.properties)