[INPUT]
    Name        tcp
    Listen      0.0.0.0
    Port        24224
    Format      json

[OUTPUT]
    Name            opensearch
    Match           *
    Host            opensearch
    Port            9200
    HTTP_User       admin
    HTTP_Passwd     admin
    Index           fluent-bit
    Suppress_Type_Name On
    tls             On
    tls.verify      Off
