# ==============================
# Server
# ==============================
server.port=8761

# ==============================
# Spring Application
# ==============================
spring.application.name=discovery-server

# ==============================
# Eureka Server
# ==============================
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Không tự bảo vệ trong môi trường DEV
eureka.server.enable-self-preservation=false

# Chu kỳ dọn dẹp các instance hết hạn (60 giây)
eureka.server.eviction-interval-timer-in-ms=60000

# ==============================
# Actuator
# ==============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
spring.config.import=optional:file:../../.env[.properties],optional:file:.env[.properties],optional:file:../../.env.dev[.properties],optional:file:.env.dev[.properties]