server.port=8888

spring.application.name=config-server

#==============================
# Eureka
#==============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#==============================
# Config Server (Cấu hình SSH)
#==============================
# 1. Thay đổi URI sang dạng SSH
spring.cloud.config.server.git.uri=git@github.com:lethanhtrong161005/bitebolt-config.git

spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true

# 2. Thêm cấu hình bỏ qua kiểm tra host key local
spring.cloud.config.server.git.ignore-local-ssh-settings=false
spring.cloud.config.server.git.strict-host-key-checking=false




#==============================
# Actuator
#==============================
management.endpoints.web.exposure.include=*